FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (including dev dependencies)
RUN npm install

# Expose port
EXPOSE 3000

# Start the app with nodemon
CMD ["npx", "nodemon", "server.js"] 