name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app-backend:latest
          
      - name: Deploy backend service
        run: |
          # Stop and remove the existing container if it exists
          docker stop todo-app-backend || true
          docker rm todo-app-backend || true
          
          # Pull the latest image
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app-backend:latest
          
          # Run the new container
          docker run -d \
            --name todo-app-backend \
            --restart always \
            -p 3000:3000 \
            -e PORT=3000 \
            -e NODE_ENV=production \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }} \
            -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app-backend:latest 